global_options:

targets:
  $default:
    builders:
      json_serializable:
        options:
          create_factory: true
          create_to_json: true
          explicit_to_json: true
          field_rename: snake
          include_if_null: false

      freezed:
        options:
          format: true
