import 'dart:convert';

import 'package:collection/collection.dart';
import 'package:swagger_to_dart/src/code/string.dart';
import 'package:swagger_to_dart/swagger_to_dart.dart';

const _methods = [
  'get',
  'put',
  'post',
  'delete',
  'options',
  'head',
  'patch',
  'trace',
  'query',
];

/// The source of a test that decodes every saved JSON example of the
/// response the generator types (the lowest 2xx, else `default`, else the
/// first) with its response model, and re-encodes it to a fixpoint; null
/// when [spec] has no such example. [library] exports the generated code.
///
/// The model of an object response is `${methodName}Response`, of an array
/// of objects `…ResponseItem`, with method names unique per client (tag) as
/// the generator makes them. Unions, primitives, maps and other responses
/// get a comment instead.
String? examplesRoundTripTest(
  Map<String, dynamic> spec, {
  required String library,
}) {
  final usedMethodNames = <String, Set<String>>{};
  final lines = <String>[];
  var tests = 0;

  for (final MapEntry(key: path, value: item)
      in (spec['paths'] as Map? ?? {}).entries) {
    for (final method in _methods) {
      if (item[method] case final Map operation) {
        final tags = [
          for (final tag in operation['tags'] as List? ?? const []) '$tag',
        ];
        final client = tags.firstOrNull ?? 'default';
        final base = Renaming.instance.renameFunction(
          '${operation['operationId'] ?? '${client}_${path}_$method'}',
        );
        var methodName = base;
        for (
          var i = 2;
          !(usedMethodNames[client] ??= {}).add(methodName);
          i++
        ) {
          methodName = '$base$i';
        }
        // A method in several clients: only its first one is checked.
        for (final tag in tags.skip(1)) {
          (usedMethodNames[tag] ??= {}).add(methodName);
        }

        final responses = operation['responses'] as Map? ?? {};
        final success = responses.keys
            .map((code) => '$code')
            .where((code) => code.startsWith('2'))
            .sorted()
            .firstOrNull;
        final typed =
            success ??
            (responses.containsKey('default')
                ? 'default'
                : responses.keys.firstOrNull);

        for (final MapEntry(key: status, value: response)
            in responses.entries) {
          final content = (response as Map)['content'] as Map? ?? {};
          final json = content.entries.firstWhereOrNull(
            (e) => _isJson('${e.key}'),
          );
          final examples = <String, Object?>{
            if ((json?.value as Map?)?['examples'] case final Map examples)
              for (final MapEntry(:key, :value) in examples.entries)
                if (value case {'value': final example}) '$key': example,
            if ((json?.value as Map?)?.containsKey('example') ?? false)
              'example': (json!.value as Map)['example'],
          };

          for (final MapEntry(key: name, value: example) in examples.entries) {
            final label = '$methodName $status example $name';
            String skip(String why) =>
                '  // ${label.replaceAll(RegExp(r'\s+'), ' ')}: skipped, $why';
            final schema = (json!.value as Map)['schema'];
            if (status != typed) {
              lines.add(skip('only the typed response has a model'));
              continue;
            }
            final model = Renaming.instance.renameClass(
              '${methodName}_response',
            );
            final literal = _literal(jsonEncode(example));
            if (_isModel(schema)) {
              tests++;
              lines.add('''
  test(${dartString('$label decodes')}, () {
    final json = jsonDecode($literal) as Map<String, dynamic>;
${_roundTrip(model)}
  });
''');
            } else if (schema case {
              'type': 'array',
              'items': final items,
            } when _isModel(items)) {
              tests++;
              lines.add('''
  test(${dartString('$label decodes')}, () {
    for (final item in jsonDecode($literal) as List) {
      // A null or primitive element fails the cast instead of being skipped.
      final json = item as Map<String, dynamic>;
${_roundTrip('${model}Item', indent: '  ')}
    }
  });
''');
            } else {
              lines.add(skip('the schema is a union, primitive or map'));
            }
          }
        }
      }
    }
  }

  if (tests == 0) return null;
  return [
    '// Generated by e2e_test.dart from the fixture\'s saved examples.',
    "import 'dart:convert';",
    '',
    "import 'package:test/test.dart';",
    "import '$library';",
    '',
    'void main() {',
    ...lines,
    '}',
    '',
  ].join('\n');
}

String _roundTrip(String model, {String indent = ''}) =>
    '''
$indent    final once = $model.fromJson(json);
$indent    final twice = $model.fromJson(
$indent      jsonDecode(jsonEncode(once.toJson())) as Map<String, dynamic>,
$indent    );
$indent    expect(twice, once);''';

/// A raw `r'''…'''` literal, else (the JSON contains `'''`) a plain one.
String _literal(String json) =>
    json.contains("'''") ? dartString(json) : "r'''$json'''";

/// An object schema with properties: a generated model class.
bool _isModel(Object? schema) =>
    schema is Map &&
    (schema['type'] ?? 'object') == 'object' &&
    schema['properties'] is Map &&
    (schema['properties'] as Map).isNotEmpty &&
    !schema.keys.any(const {'oneOf', 'anyOf', 'allOf'}.contains);

bool _isJson(String mediaType) {
  final type = mediaType.split(';').first.trim().toLowerCase();
  return type == 'application/json' ||
      type == 'text/json' ||
      type.endsWith('+json');
}
